import { Theme } from '@radix-ui/themes';
import { Crimson_Text, Inter } from 'next/font/google';
import './globals.css';
import { ClientProviders } from '@/providers';

const crimsonText = Crimson_Text({
    weight: '400',
    variable: '--font-crimson-text',
    subsets: ['latin'],
});

const inter = Inter({
    variable: '--font-inter',
    subsets: ['latin'],
});

export const metadata = {
    title: 'Tema certo - Interno',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
                <body
                    className={`${crimsonText.variable} ${inter.variable} antialiased`}
                >
                <ClientProviders>
                    <Theme>
                        {children}
                    </Theme>
                </ClientProviders>
                </body>
        </html>
    );
}
