import { Toaster } from '@/components/ui/sonner';
import { ClientProviders } from '@/providers';
import { Theme } from '@radix-ui/themes';
import { Crimson_Text, Inter } from 'next/font/google';
import './globals.css';

const crimsonText = Crimson_Text({
    weight: '600',
    variable: '--font-crimson-text',
    subsets: ['latin'],
});

const inter = Inter({
    variable: '--font-inter',
    subsets: ['latin'],
});

export const metadata = {
    title: 'Tema certo - Interno',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="pt-br">
            <head>
                <link rel="icon" href="/tema-certo-black.svg" />
                <script src="https://accounts.google.com/gsi/client" async defer></script>
            </head>
            <body
                className={`${crimsonText.variable} ${inter.variable} antialiased`}
            >
                <Theme>
                    <ClientProviders>
                        {children}
                    </ClientProviders>
                </Theme>
                <Toaster position="top-center" expand />
            </body>
        </html>
    );
}
